### ISSUE TITLE
unsupported Swift architecture

### ISSUE THREAD

**Issue by zsarsam** [AdGrid/IOS-Mobile-SDK#1]
Hi, I am getting the following error when Integrating the SDK `unsupported Swift architecture` via the Swift package manager. also get the same error when running your example code. 

I will also try to reach out via the support channel 
<img width="1230" alt="Screenshot 2023-09-01 at 1 00 31 PM" src="https://github.com/AdGrid/IOS-Mobile-SDK/assets/2651269/344d3de1-a641-448f-99ce-471f8153f98c">

**Comment by eXeShnik** [comment]
@zsarsam Hi, whats the version of XCode you are using?

**Comment by eXeShnik** [comment]
@zsarsam I Found what's wrong on lib side, problem with m-chip, cause I compiled xcframework on intel mac
Working on fixing it

**Comment by eXeShnik** [comment]
@zsarsam I fixed this issue on version 1.0.1

**Comment by zsarsam** [comment]
@eXeShnik Thanks will give it a try
